# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

steps:
  - script: echo '$(Build.BuildNumber)' # outputs customized build number like project_def_master_20200828.1

stages:
- stage: Verify
  jobs:
  - job: Verify
    pool: server
    steps: 
    - task: ContrastIntegration@2
      inputs:
        ContrastService: 'apptwo'
        Application: '75925bd3-3d06-401c-9fc6-3c8378d0d091'
        StatusFilter: 'Reported, Suspicious, Confirmed'
        AppVersionFilter: '$(Build.BuildId)'
        CriticalLimit: '1'
        HighLimit: '1'
        MediumLimit: '1'
        LowLimit: '1'
        NoteLimit: '0'


